# Generated by Django 4.2 on 2023-04-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
