# Generated by Django 4.2 on 2023-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_category_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
    ]
